import React from 'react';

const BADGE_STYLES = {
  measured: { bg: '#065f46', color: '#a7f3d0', border: '#059669', label: 'Measured', icon: '✓' },
  estimated: { bg: '#92400e', color: '#fde68a', border: '#d97706', label: 'Estimated', icon: '~' },
  'ai-generated': { bg: '#581c87', color: '#d8b4fe', border: '#9333ea', label: 'AI-Generated', icon: 'AI' },
  'crawler': { bg: '#1e3a5f', color: '#93c5fd', border: '#3b82f6', label: 'Crawler', icon: '⟳' },
  'formula': { bg: '#7c2d12', color: '#fed7aa', border: '#ea580c', label: 'Formula', icon: 'ƒx' },
  'simulated': { bg: '#713f12', color: '#fef08a', border: '#ca8a04', label: 'Simulated', icon: '◎' },
};

export default function DataSourceBadge({ source, size = 'sm', showTooltip = true, style = {} }) {
  if (!source) return null;
  const s = BADGE_STYLES[source] || BADGE_STYLES.estimated;
  const fontSize = size === 'xs' ? 9 : size === 'sm' ? 10 : 12;
  const padding = size === 'xs' ? '1px 4px' : size === 'sm' ? '2px 6px' : '3px 8px';

  return (
    <span
      title={showTooltip ? getTooltip(source) : undefined}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: 3,
        padding,
        borderRadius: 4,
        fontSize,
        fontWeight: 600,
        letterSpacing: '0.02em',
        background: s.bg,
        color: s.color,
        border: `1px solid ${s.border}`,
        lineHeight: 1.4,
        whiteSpace: 'nowrap',
        verticalAlign: 'middle',
        ...style,
      }}
    >
      <span style={{ fontSize: fontSize + 1 }}>{s.icon}</span>
      {s.label}
    </span>
  );
}

function getTooltip(source) {
  const tooltips = {
    measured: 'Data measured from a real external source (API, Lighthouse, Search Console)',
    estimated: 'Data estimated using heuristics — not directly measured from external sources',
    'ai-generated': 'Generated by an AI model — review before implementing',
    crawler: 'Data collected by crawling the page HTML directly',
    formula: 'Calculated from a formula — not real search engine data',
    simulated: 'Simulated score based on content analysis — not queried from actual platforms',
  };
  return tooltips[source] || '';
}

export function ScoreWithSource({ score, maxScore = 100, source, label, size = 'md', color }) {
  const pct = Math.min(100, Math.round((score / maxScore) * 100));
  const barColor = color || (pct >= 80 ? '#10b981' : pct >= 60 ? '#f59e0b' : '#ef4444');
  const fontSize = size === 'lg' ? 28 : size === 'md' ? 20 : 14;

  return (
    <div style={{ marginBottom: 8 }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
        <span style={{ fontSize, fontWeight: 700, color: 'var(--text-primary)' }}>{score}<span style={{ fontSize: fontSize * 0.6, opacity: 0.5 }}>/{maxScore}</span></span>
        <DataSourceBadge source={source} size="xs" />
      </div>
      {label && <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginBottom: 4 }}>{label}</div>}
      <div style={{ height: 6, borderRadius: 3, background: 'var(--bg-tertiary)', overflow: 'hidden' }}>
        <div style={{ height: '100%', width: `${pct}%`, background: barColor, borderRadius: 3, transition: 'width 0.3s' }} />
      </div>
    </div>
  );
}
