import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Bot, Zap, AlertTriangle, CheckCircle, Info, RefreshCw, ExternalLink, Sparkles, Target, MessageSquare, BarChart3, Award, Link2, MapPin, Users, ShieldCheck, Braces, Quote, LayoutGrid } from 'lucide-react';
import { api } from '../../../api';
import DataSourceBadge from '../../../components/DataSourceBadge';
import AiSuggestionStrip from '../../../components/ai/AiSuggestionStrip';
import AiSuggestionCard from '../../../components/ai/AiSuggestionCard';
import ThemeHero from '../../../components/ai/ThemeHero';
import ThemeStatCard from '../../../components/ai/ThemeStatCard';

const AI_PLAYBOOK = [
  {
    icon: Target,
    title: 'Front-load direct answers',
    tag: 'Quotable passages',
    explanation: 'AI Overviews are generated by an LLM that scans passages answering the query in a single shot. When your opening paragraph states the answer plainly — before any fluff — the model can quote it verbatim. Self-contained, declarative sentences near the top of a page are cited far more often than text buried mid-page.',
    why: 'The first ~100 words are your single most valuable AI-citation real estate.',
    steps: ['Write the full answer in the opening paragraph within the first 100 words.', 'Use one short, complete, quotable sentence.', 'Repeat the target keyword naturally inside that sentence.', 'Never bury the conclusion below an intro or story.'],
    impact: 'HIGH',
  },
  {
    icon: MessageSquare,
    title: 'Mirror conversational phrasing',
    tag: 'Query matching',
    explanation: 'People ask AI in natural language — "how do I…", "is X better than Y", "what is the best way to…". Pages phrased as a conversation, with question-style headings and Q&A blocks, match the way queries are typed and are repeatedly selected as source passages.',
    why: 'AI answers inherit the question style; your content should sound like the answer to the question.',
    steps: ['Add an FAQ block using the exact questions people type into Google/AI.', 'Write H2/H3 headings as full questions.', 'Include "how to", "vs", "best", "is it worth" phrasing for long-tail intent.'],
    impact: 'HIGH',
  },
  {
    icon: BarChart3,
    title: 'Cite stats, dates and entities',
    tag: 'Trust signals',
    explanation: 'LLMs trust passages backed by numbers, named entities, and dates. A line like "34% of teams report faster ranking with structured answers" gives the model something verifiable to cite — and attributes authority to your brand as the source.',
    why: 'Facts with numbers and named references are the most citable text on the page.',
    steps: ['Add statistics with their sources inline.', 'Reference specific tools, companies, or studies by name.', 'Include dates ("as of 2026") on claims.', 'Attribute bold claims to known authorities.'],
    impact: 'MEDIUM',
  },
  {
    icon: Award,
    title: 'Win the featured snippet',
    tag: 'Answer format',
    explanation: 'Google\'s AI Overview most often quotes the page that already holds the featured snippet — both draw from the same "answer passage" pool. Land the snippet and your content is first in line to be quoted inside the Overview.',
    why: 'Snippet + Overview citations compound: win one and you are usually cited in the other.',
    steps: ['Provide a 40–60 word direct answer above the fold.', 'Use ordered lists for "how to" and tables for comparisons.', 'Keep the snippet answer as a standalone paragraph or list.', 'Structure the answer so it can be pulled verbatim.'],
    impact: 'HIGH',
  },
  {
    icon: Link2,
    title: 'Build a citation network',
    tag: 'Earn mentions',
    explanation: 'AI checks who else mentions you. When your brand appears on industry hubs, directories, news sites, comparison pages, and review platforms, the model sees corroborating sources and includes you in answers. Zero external mentions ≈ zero AI citations.',
    why: 'Mentions outside your own site are the strongest proof of authority for AI.',
    steps: ['List the business on the top directories and platforms in your niche.', 'Pitch guest articles, interviews, and industry roundups.', 'Get included on comparison / alternative / "best of" pages.', 'Encourage customers to review you on third-party platforms.'],
    impact: 'HIGH',
  },
  {
    icon: MapPin,
    title: 'Consistent brand + NAP everywhere',
    tag: 'Entity consistency',
    explanation: 'AI cross-references your name, address, phone, and description across the web. When every profile is identical, you become one reliable entity the model can connect. Inconsistent variants get treated as noise and ignored.',
    why: 'One consistent entity is easy for AI to verify and cite; fragmented ones are skipped.',
    steps: ['Standardize name, address, phone, URL, and description across every profile.', 'Use the exact same brand capitalization everywhere.', 'Mirror your NAP in Organization / LocalBusiness schema.'],
    impact: 'MEDIUM',
  },
  {
    icon: Users,
    title: 'Community & forum presence',
    tag: 'First-hand answers',
    explanation: 'AI Overviews disproportionately quote Reddit, Quora, StackOverflow, and niche forums because they read as authentic first-hand answers. Answers you post on those platforms get cited directly — and your site earns citations when you link contextually.',
    why: 'Community threads are a top-cited source family in AI Overviews.',
    steps: ['Answer relevant questions on Reddit, Quora, and niche forums.', 'Link back to your own content naturally, not spammily.', 'Publish community-style Q&A and forum threads on your own site.'],
    impact: 'HIGH',
  },
  {
    icon: ShieldCheck,
    title: 'Prove E-E-A-T with author signals',
    tag: 'Trust & expertise',
    explanation: 'Models prefer sources with clear authorship and demonstrated expertise. Real author bios, credentials, publication dates, and citations signal trust; anonymous or stale content is deprioritized for AI citation.',
    why: 'Authoritative, attributable content wins AI citation over anonymous pages.',
    steps: ['Add author bylines with credentials and links to profiles.', 'Show "last updated" dates on every article.', 'Build a real About / team page.', 'Reference your own studies or client results with attribution.'],
    impact: 'MEDIUM',
  },
  {
    icon: Braces,
    title: 'Entity-rich structured data',
    tag: 'Schema markup',
    explanation: 'Schema lets the model map your entities — brand, products, authors, FAQs — in machine-readable form. Organization, Person, FAQPage, Article, and Product markup are proof of who you are and what you cover.',
    why: 'Structured data makes your entities undeniable to AI classifiers.',
    steps: ['Implement Organization, Person/Author, and Article schema.', 'Add FAQPage schema to Q&A content.', 'Add Product / Offer schema to commercial pages.', 'Validate everything in the Rich Results Test after each change.'],
    impact: 'MEDIUM',
  },
  {
    icon: Quote,
    title: 'Write quotable, self-contained passages',
    tag: 'Citation-ready prose',
    explanation: 'The most-cited text is a standalone sentence that makes sense in isolation — no vague pronouns, no "as discussed above". When each paragraph can be copy-pasted as an answer on its own, the model uses it verbatim.',
    why: 'Self-contained sentences are the literal unit AI quotes.',
    steps: ['End paragraphs with a punchy, self-contained conclusion sentence.', 'Avoid pronouns that point elsewhere in the article.', 'Repeat key facts so each section reads standalone.'],
    impact: 'MEDIUM',
  },
  {
    icon: LayoutGrid,
    title: 'Cover the formats AI answers in',
    tag: 'Query coverage',
    explanation: 'AI Overviews answer definition, how-to, comparison, best-of, and why-style queries. When each target page covers those angles in dedicated sections, a single URL becomes eligible to be cited across many more queries.',
    why: 'More answer formats per page = more queries where you are a candidate.',
    steps: ['Add a definition, a how-to list, a comparison, and a "best for" ranking to key pages.', 'Add an FAQ section to every pillar page.', 'Interlink the sections so AI can follow the full answer path.'],
    impact: 'MEDIUM',
  },
  {
    icon: RefreshCw,
    title: 'Track and iterate per keyword',
    tag: 'Continuous optimization',
    explanation: 'AI visibility is a moving target — competitors, updates, and your own content changes shift the citation pool. Use this monitor to watch citation rate per keyword, double down on formats that gain ground, and refresh the ones that lose it.',
    why: 'Iteration on live citation data compounds your AI visibility faster than one-time fixes.',
    steps: ['Re-check live after every content update.', 'Note which keyword formats get cited and which never do.', 'Expand winning angles; rewrite losers with new data and fresher stats.', 'Re-run a full audit monthly to refresh keyword sets.'],
    impact: 'HIGH',
  },
];

export default function AiOverviews() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [suggestions, setSuggestions] = useState(null);
  const [playbookOpen, setPlaybookOpen] = useState(0);

  const load = (silent) => {
    if (silent) setRefreshing(true); else setLoading(true);
    api.request(`/audit/${id}/ai-overviews`)
      .then(d => { setData(d); })
      .catch(() => setData({ configured: false, message: 'Failed to reach the live AI Overviews check. Backend may be offline.' }))
      .finally(() => { setLoading(false); setRefreshing(false); });
  };

  useEffect(() => { load(false); }, [id]);

  useEffect(() => {
    let alive = true;
    setSuggestions(null);
    api.getToolSuggestions(id, { tool: 'ai-overviews', limit: 6 })
      .then(res => { if (alive) setSuggestions(res?.items || []); })
      .catch(() => { if (alive) setSuggestions([]); });
    return () => { alive = false; };
  }, [id]);

  if (loading) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: 400, gap: 16 }}>
        <div style={{ width: 48, height: 48, borderRadius: '50%', border: '3px solid var(--border, #e5e7eb)', borderTopColor: 'var(--accent, #3b82f6)', animation: 'spin 0.8s linear infinite' }} />
        <div style={{ fontSize: 15, color: 'var(--text-muted, #6b7280)', fontWeight: 500 }}>Probing Google AI Overviews for your top keywords...</div>
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      </div>
    );
  }

  const summary = data?.summary || {};
  const results = data?.results || [];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <ThemeHero
        icon={Bot}
        title="AI Overviews Monitor"
        subtitle={
          <>
            Real-time check of whether <strong style={{ color: '#fff' }}>{data?.domain || 'your site'}</strong> appears in Google AI Overviews for your top keywords.
          </>
        }
        badges={[
          { icon: Sparkles, t: 'Live check' },
          { icon: CheckCircle, t: 'Citations' },
          { icon: Zap, t: 'Real-time' },
        ]}
        actions={data?.configured ? <DataSourceBadge source={data?.estimated ? 'estimated' : 'measured'} size="xs" /> : null}
      />

      <div>
        <AiSuggestionStrip auditId={id} tool="ai-overviews" title="AI Overview fixes" />
      </div>

      {suggestions && suggestions.length > 0 && (
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 }}>
            <Sparkles size={15} color="var(--accent, #3b82f6)" />
            <span style={{ fontSize: 13.5, fontWeight: 700, color: 'var(--text, #111827)' }}>Detailed AI visibility fixes</span>
            <span style={{ fontSize: 11, color: 'var(--text-muted, #6b7280)' }}>{suggestions.length} full-detail recommendations from your audit</span>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {suggestions.map((item, i) => <AiSuggestionCard key={`${item.id || item.tool}-${i}`} item={item} index={i} />)}
          </div>
        </div>
      )}

      {data?.message && data?.configured !== false && (
        <div style={{ padding: '12px 16px', borderRadius: 'var(--radius, 12px)', background: data?.estimated ? 'rgba(8,145,178,0.06)' : 'rgba(245,158,11,0.08)', border: `1px solid ${data?.estimated ? 'rgba(8,145,178,0.18)' : 'rgba(245,158,11,0.25)'}` }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12.5, color: data?.estimated ? '#0e7490' : '#b45309', lineHeight: 1.6 }}>
            {data?.estimated ? <Sparkles size={14} /> : <AlertTriangle size={14} />} {data.message}
          </div>
        </div>
      )}
      {!data?.configured ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ padding: '40px 24px', textAlign: 'center', color: '#b45309', fontSize: 13.5, background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.25)', borderRadius: 'var(--radius, 12px)', lineHeight: 1.6 }}>
            <AlertTriangle size={28} style={{ marginBottom: 8 }} />
            <div style={{ fontWeight: 700, marginBottom: 4 }}>Live AI Overviews check unavailable</div>
            <div>{data.message || 'The live check could not run right now.'} No results are shown below because nothing was measured — the zeros you may have seen previously were placeholders, not real checks.</div>
            <button onClick={() => load(true)} style={{ marginTop: 14, padding: '8px 18px', borderRadius: 'var(--radius-sm, 6px)', border: '1px solid rgba(245,158,11,0.4)', background: 'var(--bg-white, #fff)', fontSize: 12.5, fontWeight: 600, color: '#b45309', cursor: 'pointer' }}>
              <RefreshCw size={13} style={{ verticalAlign: '-2px', marginRight: 6 }} /> Try again
            </button>
          </div>
        </div>
      ) : (
        <>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: 12 }}>
            <ThemeStatCard icon={Bot} label="Keywords Checked" value={summary.keywords_checked ?? 0} color="#3b82f6" sub="Top keywords by frequency" />
            <ThemeStatCard icon={Sparkles} label="AI Overview Triggered" value={summary.with_ai_overview ?? 0} color="#f59e0b" sub="SERP showed an AI Overview" />
            <ThemeStatCard icon={CheckCircle} label="Your Site Cited" value={summary.mentioned_in_ai_overview ?? 0} color="#22c55e" sub="Mentioned inside the answer" />
            <ThemeStatCard icon={Zap} label="Citation Rate" value={`${summary.keywords_checked ? Math.round(((summary.mentioned_in_ai_overview ?? 0) / summary.keywords_checked) * 100) : 0}%`} color="#0891b2" sub="Share of keywords that cite you" />
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
            <button onClick={() => load(true)} style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 'var(--radius-sm, 6px)', border: '1px solid var(--border, #e5e7eb)', background: 'var(--bg-white, #fff)', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary, #4b5563)', cursor: 'pointer' }} disabled={refreshing}>
              <RefreshCw size={13} style={{ animation: refreshing ? 'spin 0.8s linear infinite' : 'none' }} /> {refreshing ? 'Checking...' : 'Re-check live'}
            </button>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {results.length === 0 && (
              <div style={{ padding: '40px 24px', textAlign: 'center', color: 'var(--text-muted, #6b7280)', fontSize: 13, background: 'var(--bg-white, #fff)', border: '1px solid var(--border, #e5e7eb)', borderRadius: 'var(--radius, 12px)' }}>
                <Sparkles size={28} color="var(--text-muted, #9ca3af)" style={{ marginBottom: 8 }} />
                <div>No keyword results yet. Run a full audit to generate keyword data, then re-check.</div>
              </div>
            )}
            {results.map((r, i) => (
              <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '14px 16px', borderRadius: 'var(--radius-sm, 8px)', background: 'var(--bg-white, #fff)', border: '1px solid var(--border, #e5e7eb)' }}>
                <span style={{ marginTop: 2 }}>
                  {r.mentioned_in_ai_overview ? (
                    <CheckCircle size={17} color="var(--green, #22c55e)" />
                  ) : r.has_ai_overview ? (
                    <AlertTriangle size={17} color="var(--yellow, #f59e0b)" />
                  ) : (
                    <Info size={17} color="var(--text-muted, #9ca3af)" />
                  )}
                </span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                    <span style={{ fontSize: 13.5, fontWeight: 600, color: 'var(--text, #111827)' }}>{r.keyword}</span>
                    <span style={{ fontSize: 11, fontWeight: 600, padding: '1px 8px', borderRadius: 4, background: r.mentioned_in_ai_overview ? 'rgba(34,197,94,0.12)' : r.has_ai_overview ? 'rgba(245,158,11,0.12)' : 'rgba(107,114,128,0.12)', color: r.mentioned_in_ai_overview ? '#22c55e' : r.has_ai_overview ? '#f59e0b' : '#6b7280' }}>
                      {r.mentioned_in_ai_overview ? 'Cited in AI Overview' : r.has_ai_overview ? 'AI Overview shown — not you' : 'No AI Overview'}
                    </span>
                  </div>
                  {r.ai_overview_text && (
                    <div style={{ fontSize: 12, color: 'var(--text-muted, #6b7280)', marginTop: 6, lineHeight: 1.55, fontStyle: 'italic' }}>"{r.ai_overview_text}"</div>
                  )}
                  {r.top_cited_domains?.length > 0 && (
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexWrap: 'wrap', marginTop: 6 }}>
                      <ExternalLink size={11} color="var(--text-muted, #9ca3af)" />
                      <span style={{ fontSize: 11.5, color: 'var(--text-muted, #6b7280)' }}>Top cited domains:</span>
                      {r.top_cited_domains.map((d, di) => (
                        <span key={di} style={{ fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 4, background: 'rgba(59,130,246,0.08)', color: 'var(--accent, #3b82f6)' }}>{d}</span>
                      ))}
                    </div>
                  )}
                  {r.error && <div style={{ fontSize: 11.5, color: '#ef4444', marginTop: 4 }}>{r.error}</div>}
                </div>
              </div>
            ))}
          </div>

          <div style={{ padding: '18px 20px', borderRadius: 'var(--radius, 12px)', background: 'rgba(8,145,178,0.05)', border: '1px solid rgba(8,145,178,0.15)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
              <Zap size={15} color="#0e7490" />
              <span style={{ fontSize: 14, fontWeight: 700, color: '#0e7490' }}>AI Visibility Growth Playbook</span>
              <span style={{ fontSize: 11.5, color: 'var(--text-muted, #6b7280)' }}>— {AI_PLAYBOOK.length} full recommendations to get cited by AI Overviews</span>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
              {AI_PLAYBOOK.map((p, i) => {
                const Icon = p.icon;
                const open = playbookOpen === i;
                return (
                  <div key={i} style={{ borderRadius: 'var(--radius-sm, 8px)', background: 'var(--bg-white, #fff)', border: '1px solid var(--border, #e5e7eb)', overflow: 'hidden' }}>
                    <button
                      onClick={() => setPlaybookOpen(open ? -1 : i)}
                      style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 10, padding: '11px 14px', background: 'transparent', border: 'none', cursor: 'pointer', textAlign: 'left' }}
                    >
                      <span style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 30, height: 30, borderRadius: 8, background: 'rgba(8,145,178,0.1)', color: '#0e7490', flexShrink: 0 }}>
                        <Icon size={15} />
                      </span>
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text, #111827)' }}>{i + 1}. {p.title}</div>
                        <div style={{ fontSize: 11, color: 'var(--text-muted, #6b7280)', marginTop: 1 }}>{p.tag}</div>
                      </div>
                      <span style={{ fontSize: 10.5, fontWeight: 700, padding: '2px 8px', borderRadius: 4, background: p.impact === 'HIGH' ? 'rgba(34,197,94,0.12)' : 'rgba(245,158,11,0.12)', color: p.impact === 'HIGH' ? '#22c55e' : '#f59e0b', flexShrink: 0 }}>
                        {p.impact} IMPACT
                      </span>
                    </button>
                    {open && (
                      <div style={{ padding: '12px 14px', borderTop: '1px solid var(--border, #e5e7eb)', display: 'flex', flexDirection: 'column', gap: 10 }}>
                        <div style={{ fontSize: 12.5, color: 'var(--text-secondary, #4b5563)', lineHeight: 1.7 }}>{p.explanation}</div>
                        <div style={{ display: 'flex', gap: 8 }}>
                          <span style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: 0.3, color: '#0e7490', flexShrink: 0, paddingTop: 1 }}>WHY</span>
                          <span style={{ fontSize: 12, color: 'var(--text-secondary, #4b5563)', lineHeight: 1.6 }}>{p.why}</span>
                        </div>
                        <div>
                          <div style={{ fontSize: 10.5, fontWeight: 700, letterSpacing: 0.3, color: '#0e7490', marginBottom: 6 }}>HOW TO DO IT</div>
                          <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                            {p.steps.map((s, si) => (
                              <div key={si} style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                                <CheckCircle size={13} color="#22c55e" style={{ marginTop: 2, flexShrink: 0 }} />
                                <span style={{ fontSize: 12, color: 'var(--text-secondary, #4b5563)', lineHeight: 1.55 }}>{s}</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
