import jsPDF from 'jspdf';

const C = {
  darkBlue: [30, 58, 95],
  accent: [59, 130, 246],
  white: [255, 255, 255],
  black: [17, 24, 39],
  gray: [107, 114, 128],
  lightGray: [243, 244, 246],
  border: [229, 231, 235],
  critical: [220, 38, 38],
  high: [245, 158, 11],
  medium: [59, 130, 246],
  low: [34, 197, 94],
  green: [5, 150, 105],
  red: [220, 38, 38],
  yellow: [217, 119, 6],
};

function scoreColor(s) { return s >= 75 ? C.green : s >= 50 ? C.yellow : C.red; }
function scoreHex(s) { return s >= 75 ? '#059669' : s >= 50 ? '#D97706' : '#DC2626'; }
function sevColor(s) { return ({ CRITICAL: C.critical, HIGH: C.high, MEDIUM: C.medium, LOW: C.low })[s] || C.gray; }
function sevHex(s) { return ({ CRITICAL: '#DC2626', HIGH: '#F59E0B', MEDIUM: '#3B82F6', LOW: '#22C55E' })[s] || '#6B7280'; }

function wrap(doc, text, maxW) {
  if (!text) return [''];
  const lines = doc.splitTextToSize(String(text).replace(/[^\x20-\x7E\u00A0-\u024F]/g, ''), maxW);
  return Array.isArray(lines) ? lines : [String(text)];
}

function footer(doc, page) {
  const total = doc.getNumberOfPages();
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by AI SEO Intelligence Platform', 15, h - 8);
  doc.text(`Page ${page} of ${total}`, w - 15, h - 8, { align: 'right' });
  doc.setDrawColor(229, 231, 235);
  doc.line(15, h - 12, w - 15, h - 12);
}

function header(doc, title, y = 15) {
  doc.setFillColor(...C.darkBlue);
  doc.rect(0, 0, 210, y + 14, 'F');
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text(title, 15, y + 6);
  return y + 22;
}

function subHeader(doc, title, y, color = C.darkBlue) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...color);
  doc.text(title, 15, y);
  doc.setDrawColor(...color);
  doc.setLineWidth(0.5);
  doc.line(15, y + 2, 210 - 15, y + 2);
  return y + 8;
}

function table(doc, { headers, rows, x, y, colWidths, opts = {} }) {
  const { fontSize = 7.5, rowH = 6, maxRows } = opts;
  const pH = doc.internal.pageSize.getHeight() - 20;
  let cy = y;
  const tw = colWidths.reduce((a, b) => a + b, 0);

  // Header
  doc.setFontSize(fontSize);
  doc.setFont('helvetica', 'bold');
  doc.setFillColor(...C.darkBlue);
  doc.setTextColor(...C.white);
  let ox = 0;
  headers.forEach((h, i) => {
    doc.text(String(h).substring(0, 30), x + ox + 2, cy + 4.5);
    ox += colWidths[i];
  });
  doc.rect(x, cy, tw, rowH, 'F');
  cy += rowH;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...C.black);
  const displayRows = maxRows ? rows.slice(0, maxRows) : rows;

  displayRows.forEach((row, ri) => {
    const cellLines = row.map((cell, ci) => wrap(doc, cell, colWidths[ci] - 4));
    const maxLines = Math.max(...cellLines.map(l => l.length));
    const ch = Math.max(rowH, maxLines * (fontSize * 0.45) + 2);

    if (cy + ch > pH) {
      doc.addPage();
      footer(doc, doc.getNumberOfPages());
      cy = 20;
      // Repeat header
      doc.setFont('helvetica', 'bold');
      doc.setFillColor(...C.darkBlue);
      doc.setTextColor(...C.white);
      let ox2 = 0;
      headers.forEach((h, i) => {
        doc.text(String(h).substring(0, 30), x + ox2 + 2, cy + 4.5);
        ox2 += colWidths[i];
      });
      doc.rect(x, cy, tw, rowH, 'F');
      cy += rowH;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...C.black);
    }

    if (ri % 2 === 0) {
      doc.setFillColor(248, 249, 250);
      doc.rect(x, cy, tw, ch, 'F');
    }

    cellLines.forEach((lines, ci) => {
      const ox = colWidths.slice(0, ci).reduce((a, b) => a + b, 0);
      lines.forEach((line, li) => {
        doc.text(String(line), x + ox + 2, cy + 3.5 + li * (fontSize * 0.45));
      });
    });
    cy += ch;
  });
  return cy;
}

function scoreCircle(doc, x, y, label, score, size = 28) {
  const col = scoreColor(score);
  doc.setFillColor(248, 249, 250);
  doc.circle(x + size / 2, y + size / 2, size / 2, 'F');
  doc.setDrawColor(...col);
  doc.setLineWidth(1.5);
  doc.circle(x + size / 2, y + size / 2, size / 2, 'S');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...col);
  doc.text(String(Math.round(score)), x + size / 2, y + size / 2 + 1, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.setTextColor(...C.gray);
  doc.text(label, x + size / 2, y + size + 5, { align: 'center' });
}

function grade(score) {
  if (score >= 90) return 'A+';
  if (score >= 80) return 'A';
  if (score >= 70) return 'B+';
  if (score >= 60) return 'B';
  if (score >= 50) return 'C';
  if (score >= 40) return 'D';
  return 'F';
}

export function generatePDFReport(reportData) {
  try {
    const doc = new jsPDF('p', 'mm', 'a4');
    const W = 210, M = 15, cW = W - 2 * M;
    const site = reportData.site_summary || {};
    const issues = reportData.issues_summary || {};
    const criticals = reportData.critical_issues || [];
    const recs = reportData.top_recommendations || [];
    const pages = reportData.page_scores || [];
    const overall = site.overall_score || 0;

    if (typeof issues.by_severity === 'string') try { issues.by_severity = JSON.parse(issues.by_severity); } catch {}
    if (typeof issues.by_category === 'string') try { issues.by_category = JSON.parse(issues.by_category); } catch {}

    // ==================== PAGE 1: COVER ====================
    doc.setFillColor(...C.darkBlue);
    doc.rect(0, 0, W, 297, 'F');
    // Accent bar
    doc.setFillColor(...C.accent);
    doc.rect(0, 90, W, 4, 'F');

    doc.setTextColor(...C.white);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(32);
    doc.text('AI SEO Intelligence', W / 2, 55, { align: 'center' });
    doc.text('Report', W / 2, 70, { align: 'center' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.text(reportData.audit_url || '', W / 2, 110, { align: 'center' });

    doc.setFontSize(10);
    doc.text(`Generated: ${reportData.generated_at || new Date().toISOString()}`, W / 2, 122, { align: 'center' });
    doc.text(`Pages Crawled: ${site.total_pages || 0}  |  Issues Found: ${site.total_issues || 0}`, W / 2, 132, { align: 'center' });

    // Score box
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(60, 150, 90, 60, 5, 5, 'F');
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('OVERALL SCORE', W / 2, 162, { align: 'center' });
    const sc = scoreColor(overall);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(42);
    doc.setTextColor(...sc);
    doc.text(String(Math.round(overall)), W / 2, 188, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(14);
    doc.text(`Grade: ${grade(overall)}`, W / 2, 200, { align: 'center' });

    // Mini scores
    const miniScores = [
      { label: 'SEO', score: site.seo_score },
      { label: 'Technical', score: site.technical_score },
      { label: 'Content', score: site.content_score },
      { label: 'AEO', score: site.aeo_score },
      { label: 'GEO', score: site.geo_score },
      { label: 'AI Visibility', score: site.ai_visibility_score },
    ];
    miniScores.forEach((s, i) => {
      const col = i % 3;
      const row = Math.floor(i / 3);
      const bx = M + col * (cW / 3);
      const by = 225 + row * 22;
      doc.setFontSize(8);
      doc.setTextColor(200, 200, 200);
      doc.text(s.label, bx + 15, by);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(...scoreColor(s.score || 0));
      doc.text(String(Math.round(s.score || 0)), bx + 15, by + 12);
      doc.setFont('helvetica', 'normal');
    });

    footer(doc, 1);

    // ==================== PAGE 2: EXECUTIVE SUMMARY ====================
    doc.addPage();
    footer(doc, 2);
    let y = header(doc, 'Executive Summary');
    y += 2;

    // Score grid
    y = subHeader(doc, 'Site Scores', y);
    y += 4;
    miniScores.forEach((s, i) => {
      const col = i % 6;
      const bx = M + col * (cW / 6);
      scoreCircle(doc, bx, y, s.label, s.score || 0, 24);
    });
    y += 42;

    // Overview stats
    y = subHeader(doc, 'Overview', y);
    y += 4;
    const stats = [
      ['Total Pages Crawled', String(site.total_pages || 0)],
      ['Total Issues Found', String(site.total_issues || 0)],
      ['Total Recommendations', String(site.total_recommendations || 0)],
      ['Overall Score', `${overall}/100 (${grade(overall)})`],
    ];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    stats.forEach(([label, val]) => {
      doc.setTextColor(...C.gray);
      doc.text(label, M + 2, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(val, M + 80, y);
      doc.setFont('helvetica', 'normal');
      y += 7;
    });
    y += 4;

    // Page Type Breakdown
    const ptBreakdown = site.page_type_breakdown || {};
    if (Object.keys(ptBreakdown).length > 0) {
      y = subHeader(doc, 'Page Type Breakdown', y);
      y += 4;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      Object.entries(ptBreakdown).sort((a, b) => b[1] - a[1]).forEach(([type, count]) => {
        doc.setTextColor(...C.gray);
        doc.text(`${type}:`, M + 2, y);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...C.black);
        doc.text(String(count), M + 55, y);
        doc.setFont('helvetica', 'normal');
        y += 6;
      });
      y += 4;
    }

    // Issues by severity
    y = subHeader(doc, 'Issues by Severity', y);
    y += 2;
    const sevs = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
    y = table(doc, {
      headers: ['Severity', 'Count', '% of Total'],
      rows: sevs.map(s => [s, String((issues.by_severity || {})[s] || 0), `${Math.round(((issues.by_severity || {})[s] || 0) / Math.max(issues.total || 1, 1) * 100)}%`]),
      x: M, y, colWidths: [cW * 0.35, cW * 0.3, cW * 0.35],
    });
    y += 4;

    // Issues by category
    y = subHeader(doc, 'Issues by Category', y);
    y += 2;
    const cats = Object.keys(issues.by_category || {}).sort((a, b) => (issues.by_category[b] || 0) - (issues.by_category[a] || 0));
    y = table(doc, {
      headers: ['Category', 'Count', '% of Total'],
      rows: cats.map(c => [c, String((issues.by_category || {})[c] || 0), `${Math.round(((issues.by_category || {})[c] || 0) / Math.max(issues.total || 1, 1) * 100)}%`]),
      x: M, y, colWidths: [cW * 0.35, cW * 0.3, cW * 0.35],
    });

    footer(doc, 2);

    // ==================== PAGE 3: CRITICAL ISSUES ====================
    doc.addPage();
    footer(doc, 3);
    y = header(doc, 'Critical Issues');
    y += 2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...C.gray);
    doc.text(`Showing top ${criticals.length} high-severity issues that need immediate attention`, M, y);
    y += 8;

    if (criticals.length === 0) {
      doc.setFont('helvetica', 'italic');
      doc.text('No critical issues found.', M, y);
    } else {
      y = table(doc, {
        headers: ['#', 'Page', 'Issue', 'Severity', 'Description', 'Fix'],
        rows: criticals.map((issue, i) => [
          String(i + 1),
          (issue.page || '').replace('https://www.datavicloud.ai', '').substring(0, 35) || '/',
          issue.signal || '',
          issue.severity || '',
          (issue.description || '').substring(0, 60),
          (issue.fix || '').substring(0, 55),
        ]),
        x: M, y,
        colWidths: [8, 30, 25, 16, 55, 56],
        opts: { rowH: 7 },
      });
    }

    footer(doc, 3);

    // ==================== PAGE 3b: CONTEXT-SPECIFIC ISSUES ====================
    const ctxIssues = reportData.context_issues || [];
    if (ctxIssues.length > 0) {
      doc.addPage();
      footer(doc, doc.getNumberOfPages());
      y = header(doc, 'Context-Specific Issues');
      y += 2;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(...C.gray);
      doc.text(`${ctxIssues.length} page-type-specific issues detected (not generic SEO issues)`, M, y);
      y += 8;

      y = table(doc, {
        headers: ['#', 'Page Type', 'Page', 'Issue', 'Severity', 'Description', 'Fix'],
        rows: ctxIssues.slice(0, 40).map((issue, i) => [
          String(i + 1),
          (issue.page_type || '').substring(0, 12),
          (issue.page_url || '').replace('https://www.datavicloud.ai', '').substring(0, 28) || '/',
          (issue.signal_name || '').substring(0, 25),
          issue.severity || '',
          (issue.description || '').substring(0, 50),
          (issue.fix || '').substring(0, 45),
        ]),
        x: M, y,
        colWidths: [8, 16, 28, 25, 14, 48, 51],
        opts: { rowH: 7 },
      });
      footer(doc, doc.getNumberOfPages());
    }

    // ==================== PAGE 4: RECOMMENDATIONS ====================
    doc.addPage();
    footer(doc, 4);
    y = header(doc, 'Recommendations');
    y += 2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...C.gray);
    doc.text(`${recs.length} recommendations ranked by priority`, M, y);
    y += 8;

    if (recs.length === 0) {
      doc.setFont('helvetica', 'italic');
      doc.text('No recommendations available.', M, y);
    } else {
      recs.forEach((rec, i) => {
        if (y > 260) {
          doc.addPage();
          footer(doc, doc.getNumberOfPages());
          y = 20;
        }
        const sc = sevColor(rec.priority);
        doc.setFillColor(sc[0], sc[1], sc[2]);
        doc.rect(M, y, 2, 24, 'F');
        doc.setFillColor(248, 249, 250);
        doc.rect(M + 4, y, cW - 4, 24, 'F');

        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(...C.black);
        doc.text(`${i + 1}. ${rec.issue || 'Issue'}`, M + 8, y + 5);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(...C.gray);
        const catPri = `${rec.category || ''} · ${rec.priority || ''}`;
        doc.text(catPri, M + 8, y + 10);

        doc.setFontSize(8);
        doc.setTextColor(80, 80, 80);
        const fixLines = wrap(doc, `Fix: ${rec.exact_fix || ''}`, cW - 16);
        doc.text(fixLines.slice(0, 2), M + 8, y + 16);

        if (rec.expected_impact) {
          doc.setTextColor(...C.green);
          doc.text(`Impact: ${rec.expected_impact}`, M + 8, y + 22);
        }
        y += 28;
      });
    }

    footer(doc, doc.getNumberOfPages());

    // ==================== PAGE 5: PAGE SCORES (ALL) ====================
    doc.addPage();
    footer(doc, doc.getNumberOfPages());
    y = header(doc, `Page Scores (${pages.length} Pages)`);
    y += 2;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...C.gray);
    doc.text('All pages sorted by overall score (lowest first) — focus improvements here', M, y);
    y += 8;

    if (pages.length === 0) {
      doc.setFont('helvetica', 'italic');
      doc.text('No page scores available.', M, y);
    } else {
      const sorted = [...pages].sort((a, b) => (a.scores?.overall || 0) - (b.scores?.overall || 0));
      y = table(doc, {
        headers: ['#', 'Page URL', 'Type', 'SEO', 'Content', 'AEO', 'GEO', 'Tech', 'Overall'],
        rows: sorted.map((p, i) => {
          const s = p.scores || {};
          const shortUrl = (p.url || '').replace('https://www.datavicloud.ai', '').substring(0, 38) || '/';
          return [
            String(i + 1),
            shortUrl,
            (p.page_type || 'UNK').substring(0, 8),
            String(Math.round(s.seo || 0)),
            String(Math.round(s.content || 0)),
            String(Math.round(s.aeo || 0)),
            String(Math.round(s.geo || 0)),
            String(Math.round(s.technical || 0)),
            String(Math.round(s.overall || 0)),
          ];
        }),
        x: M, y,
        colWidths: [8, 44, 14, 14, 14, 14, 14, 14, 18],
        opts: { fontSize: 7, rowH: 5.5 },
      });
    }

    footer(doc, doc.getNumberOfPages());

    // ==================== PAGE 6: CONTENT ANALYSIS ====================
    doc.addPage();
    footer(doc, doc.getNumberOfPages());
    y = header(doc, 'Content Analysis');
    y += 2;
    y = subHeader(doc, 'Content Overview', y);
    y += 4;

    const contentData = reportData.content_analysis || {};
    const contentStats = [
      ['Content Score', `${site.content_score || 0}/100`],
      ['Average Word Count', String(contentData.avg_word_count || 'N/A')],
      ['Thin Content Pages', String(contentData.thin_content_count || 0)],
    ];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    contentStats.forEach(([label, val]) => {
      doc.setTextColor(...C.gray);
      doc.text(label, M + 2, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(val, M + 80, y);
      doc.setFont('helvetica', 'normal');
      y += 7;
    });

    // Thin content pages
    const thinUrls = contentData.thin_content_urls || [];
    if (thinUrls.length > 0) {
      y += 4;
      y = subHeader(doc, 'Thin Content Pages', y);
      y += 4;
      y = table(doc, {
        headers: ['#', 'Page URL'],
        rows: thinUrls.slice(0, 30).map((url, i) => [
          String(i + 1),
          String(url).replace('https://www.datavicloud.ai', '').substring(0, 80) || '/',
        ]),
        x: M, y, colWidths: [10, cW - 10],
      });
    }

    footer(doc, doc.getNumberOfPages());

    // ==================== PAGE 7: INTERNAL LINKING ====================
    doc.addPage();
    footer(doc, doc.getNumberOfPages());
    y = header(doc, 'Internal Linking Analysis');
    y += 2;

    const linkData = reportData.internal_links || {};
    y = subHeader(doc, 'Link Overview', y);
    y += 4;
    const linkStats = [
      ['Total Pages', String(linkData.total_pages || 0)],
      ['Avg Internal Links/Page', String(linkData.avg_internal_links || 0)],
      ['Avg External Links/Page', String(linkData.avg_external_links || 0)],
      ['Pages With No Internal Links', String(linkData.pages_with_no_internal_links || 0)],
      ['Orphan Pages', String(linkData.orphan_pages || 0)],
    ];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    linkStats.forEach(([label, val]) => {
      doc.setTextColor(...C.gray);
      doc.text(label, M + 2, y);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C.black);
      doc.text(val, M + 90, y);
      doc.setFont('helvetica', 'normal');
      y += 7;
    });

    // No-link pages
    const noLinks = linkData.no_links_urls || [];
    if (noLinks.length > 0) {
      y += 4;
      y = subHeader(doc, 'Pages With No Internal Links', y);
      y += 4;
      y = table(doc, {
        headers: ['#', 'Page URL'],
        rows: noLinks.slice(0, 25).map((url, i) => [
          String(i + 1),
          String(url).replace('https://www.datavicloud.ai', '').substring(0, 80) || '/',
        ]),
        x: M, y, colWidths: [10, cW - 10],
      });
    }

    footer(doc, doc.getNumberOfPages());

    // ==================== PAGE 8: ALL ISSUES BY CATEGORY ====================
    doc.addPage();
    footer(doc, doc.getNumberOfPages());
    y = header(doc, 'Issues Breakdown');
    y += 2;

    const allIssues = reportData.issues_by_category || issues.by_category || {};
    const issueCategories = Object.keys(allIssues).sort((a, b) => {
      const aArr = Array.isArray(allIssues[a]) ? allIssues[a] : [];
      const bArr = Array.isArray(allIssues[b]) ? allIssues[b] : [];
      return bArr.length - aArr.length;
    });

    if (typeof allIssues === 'object' && !Array.isArray(allIssues)) {
      issueCategories.forEach(cat => {
        if (y > 250) {
          doc.addPage();
          footer(doc, doc.getNumberOfPages());
          y = 20;
        }
        const items = Array.isArray(allIssues[cat]) ? allIssues[cat] : [];
        if (items.length === 0) return;
        y = subHeader(doc, `${cat} (${items.length} issues)`, y);
        y += 2;

        y = table(doc, {
          headers: ['Severity', 'Signal', 'Description', 'Fix'],
          rows: items.slice(0, 15).map(issue => [
            issue.severity || 'LOW',
            (issue.signal_name || '').substring(0, 20),
            (issue.description || '').substring(0, 65),
            (issue.fix || '').substring(0, 60),
          ]),
          x: M, y,
          colWidths: [16, 28, 70, 76],
          opts: { rowH: 6 },
        });
        y += 4;
      });
    }

    footer(doc, doc.getNumberOfPages());

    // ==================== FINAL: TOTAL PAGES ====================
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      footer(doc, i);
    }

    return doc.output('blob');
  } catch (error) {
    console.error('PDF generation error:', error);
    const fallback = new jsPDF('p', 'mm', 'a4');
    fallback.setFontSize(16);
    fallback.text('Error generating PDF report', 15, 30);
    fallback.setFontSize(10);
    fallback.text(String(error.message || error), 15, 42);
    fallback.text(String(error.stack || ''), 15, 52);
    return fallback.output('blob');
  }
}
